TARGET = ../lib/libcore.so
OBJS  = usersrc.o usersub.o add_ntuple.o int2char.o util.o encgeneric.o

include ../common.mk

usersrc.o:  analyslogic.fh analysevent.fh rawdata.fh commonprm.fh runstat.fh
encgeneric.o:  analyslogic.fh
